version: '3'

services:
  php:
    build:
      dockerfile: .docker/php-fpm/Dockerfile
      context: .
    volumes:
      - ./src:/usr/share/nginx/html

  webserver:
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "8080:80"
    links:
      - php
